spring:
  application:
    name: Blink Link
    datasource:
      url: jdbc:h2:mem:blinklinkdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    port: 8080
