package pablo.tzeliks.blink_link.application.url.usecase;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import pablo.tzeliks.blink_link.application.url.dto.CreateUrlRequest;
import pablo.tzeliks.blink_link.application.url.dto.UrlResponse;
import pablo.tzeliks.blink_link.application.url.mapper.UrlDtoMapper;
import pablo.tzeliks.blink_link.domain.url.exception.InvalidUrlException;
import pablo.tzeliks.blink_link.domain.url.model.Url;
import pablo.tzeliks.blink_link.domain.url.ports.ShortenerPort;
import pablo.tzeliks.blink_link.domain.url.ports.UrlRepositoryPort;
import pablo.tzeliks.blink_link.infrastructure.exception.EncoderException;

/**
 * Use case for shortening long URLs into compact short codes.
 * <p>
 * This service implements the core business logic for creating shortened URLs.
 * It orchestrates the following operations:
 * <ol>
 *   <li><b>ID Generation:</b> Obtains a unique ID from the database sequence</li>
 *   <li><b>Base62 Encoding:</b> Converts the numeric ID into a short, URL-safe code</li>
 *   <li><b>Domain Model Creation:</b> Constructs a {@link Url} domain object with validations</li>
 *   <li><b>Persistence:</b> Saves the URL mapping to the database</li>
 * </ol>
 * <p>
 * <b>Base62 Encoding Logic:</b>
 * <p>
 * The short code is generated by first obtaining a unique sequential ID from PostgreSQL,
 * then encoding that ID using the Base62 algorithm. This approach ensures:
 * <ul>
 *   <li>Uniqueness: Each ID maps to a unique short code</li>
 *   <li>Consistency: The same ID always produces the same short code</li>
 *   <li>Compactness: Base62 encoding produces shorter strings than decimal representation</li>
 *   <li>URL-safety: Uses only alphanumeric characters (a-z, A-Z, 0-9)</li>
 * </ul>
 * <p>
 * <b>Error Handling:</b>
 * <ul>
 *   <li>Throws {@link InvalidUrlException} if the URL format is invalid</li>
 *   <li>Throws {@link InvalidUrlException} if the encoding process fails</li>
 *   <li>Throws {@link InvalidUrlException} if the URL doesn't start with http/https</li>
 * </ul>
 * <p>
 * <b>Transaction Management:</b>
 * <p>
 * This method is annotated with {@code @Transactional}, ensuring that ID generation,
 * encoding, and database insertion are executed within a single transaction. If any
 * step fails, the entire operation is rolled back.
 *
 * @author Pablo Tzeliks
 * @version 2.0.0
 * @since 1.0.0
 * @see Base62Encoder
 * @see UrlRepositoryPort
 */
@Service
public class ShortenUrlUseCase {

    private final ShortenerPort shortener;
    private final UrlRepositoryPort repository;
    private final UrlDtoMapper mapper;

    public ShortenUrlUseCase(ShortenerPort shortener, UrlRepositoryPort repository, UrlDtoMapper mapper) {
        this.shortener = shortener;
        this.repository = repository;
        this.mapper = mapper;
    }

    /**
     * Executes the URL shortening process.
     * <p>
     * This method coordinates the entire URL shortening workflow:
     * <ol>
     *   <li>Retrieves the next available ID from the database sequence</li>
     *   <li>Encodes the ID into a Base62 short code</li>
     *   <li>Creates a domain model with validation</li>
     *   <li>Persists the URL mapping to the database</li>
     *   <li>Returns the result as a DTO with the complete short URL</li>
     * </ol>
     * <p>
     * <b>Validations Applied:</b>
     * <ul>
     *   <li>URL must not be blank ({@code @NotBlank} on request)</li>
     *   <li>URL must be in valid format ({@code @URL} on request)</li>
     *   <li>URL must start with http/https (domain-level validation)</li>
     *   <li>ID must not be null or negative (encoding validation)</li>
     * </ul>
     *
     * @param request the URL creation request containing the original long URL
     * @return a {@link UrlResponse} containing the original URL, short code, full short URL, and creation timestamp
     * @throws InvalidUrlException if the URL is invalid, blank, or doesn't start with http/https
     * @throws EncoderException if the ID cannot be encoded (wrapped as InvalidUrlException)
     */
    @Transactional
    public UrlResponse execute(CreateUrlRequest request) {

        Long id = repository.nextId();
        String shortCode;

        try {

            shortCode = shortener.encode(id);
        } catch (EncoderException e) {

            throw new InvalidUrlException(e.getMessage());
        }

        Url url = mapper.toDomain(request, id, shortCode);
        Url savedUrl = repository.save(url);

        return mapper.toDto(savedUrl);
    }
}
